"use client";

import dynamic from "next/dynamic";
import type { ComponentType } from "react";

function Loading() {
  return (
    <div className="card grid place-items-center p-12">
      <div
        className="h-8 w-8 animate-spin rounded-full border-2 border-t-transparent"
        style={{ borderColor: "var(--brand)", borderTopColor: "transparent" }}
        aria-label="Loading tool"
      />
    </div>
  );
}

// Client-only tool components (browser APIs: canvas, File, workers).
const COMPONENTS: Record<string, ComponentType> = {
  "image-compressor": dynamic(() => import("./ImageCompressor"), { ssr: false, loading: Loading }),
  "image-converter": dynamic(() => import("./ImageConverter"), { ssr: false, loading: Loading }),
  "image-resizer": dynamic(() => import("./ImageResizer"), { ssr: false, loading: Loading }),
  "blur-image": dynamic(() => import("./ImageBlur"), { ssr: false, loading: Loading }),
  "add-watermark": dynamic(() => import("./ImageWatermark"), { ssr: false, loading: Loading }),
  "rotate-image": dynamic(() => import("./ImageRotate"), { ssr: false, loading: Loading }),
  "flip-image": dynamic(() => import("./ImageFlip"), { ssr: false, loading: Loading }),
  "image-to-pdf": dynamic(() => import("./ImageToPdf"), { ssr: false, loading: Loading }),
  "color-picker": dynamic(() => import("./ColorPicker"), { ssr: false, loading: Loading }),
  "palette-generator": dynamic(() => import("./PaletteGenerator"), { ssr: false, loading: Loading }),
  "exif-viewer": dynamic(() => import("./ExifViewer"), { ssr: false, loading: Loading }),
  "remove-background": dynamic(() => import("./BackgroundRemover"), { ssr: false, loading: Loading }),
  "pdf-merge": dynamic(() => import("./PdfMerge"), { ssr: false, loading: Loading }),
  "pdf-split": dynamic(() => import("./PdfSplit"), { ssr: false, loading: Loading }),
  "pdf-compressor": dynamic(() => import("./PdfCompressor"), { ssr: false, loading: Loading }),
  "pdf-rotate": dynamic(() => import("./PdfRotate"), { ssr: false, loading: Loading }),
  "pdf-page-numbers": dynamic(() => import("./PdfPageNumbers"), { ssr: false, loading: Loading }),
  "pdf-protect": dynamic(() => import("./PdfProtect"), { ssr: false, loading: Loading }),
  "pdf-unlock": dynamic(() => import("./PdfUnlock"), { ssr: false, loading: Loading }),
  "pdf-extract-images": dynamic(() => import("./PdfExtractImages"), { ssr: false, loading: Loading }),
  "pdf-ocr": dynamic(() => import("./PdfOcr"), { ssr: false, loading: Loading }),
  "word-counter": dynamic(() => import("./WordCounter"), { ssr: false, loading: Loading }),
  "case-converter": dynamic(() => import("./CaseConverter"), { ssr: false, loading: Loading }),
  "text-diff": dynamic(() => import("./TextDiff"), { ssr: false, loading: Loading }),
  "text-formatter": dynamic(() => import("./TextFormatter"), { ssr: false, loading: Loading }),
  "markdown-editor": dynamic(() => import("./MarkdownEditor"), { ssr: false, loading: Loading }),
  "notes": dynamic(() => import("./NotesApp"), { ssr: false, loading: Loading }),
  "character-counter": dynamic(() => import("./CharacterCounter"), { ssr: false, loading: Loading }),
  "remove-duplicate-lines": dynamic(() => import("./RemoveDuplicateLines"), { ssr: false, loading: Loading }),
  "sort-lines": dynamic(() => import("./SortLines"), { ssr: false, loading: Loading }),
  "reverse-text": dynamic(() => import("./ReverseText"), { ssr: false, loading: Loading }),
  "random-text-generator": dynamic(() => import("./RandomTextGenerator"), { ssr: false, loading: Loading }),
  "lorem-ipsum": dynamic(() => import("./LoremIpsum"), { ssr: false, loading: Loading }),
  "remove-empty-lines": dynamic(() => import("./RemoveEmptyLines"), { ssr: false, loading: Loading }),
  "find-and-replace": dynamic(() => import("./FindReplace"), { ssr: false, loading: Loading }),
  "trim-whitespace": dynamic(() => import("./TrimWhitespace"), { ssr: false, loading: Loading }),
  "unicode-inspector": dynamic(() => import("./UnicodeInspector"), { ssr: false, loading: Loading }),
  "emoji-picker": dynamic(() => import("./EmojiPicker"), { ssr: false, loading: Loading }),
  "fancy-text-generator": dynamic(() => import("./FancyTextGenerator"), { ssr: false, loading: Loading }),
  "slug-generator": dynamic(() => import("./SlugGenerator"), { ssr: false, loading: Loading }),
  "html-escape": dynamic(() => import("./HtmlEscape"), { ssr: false, loading: Loading }),
  "url-encode": dynamic(() => import("./UrlEncode"), { ssr: false, loading: Loading }),
  "base64": dynamic(() => import("./Base64Tool"), { ssr: false, loading: Loading }),
  // Developer Tools
  "json-formatter": dynamic(() => import("./JsonFormatter"), { ssr: false, loading: Loading }),
  "json-validator": dynamic(() => import("./JsonValidator"), { ssr: false, loading: Loading }),
  "yaml-formatter": dynamic(() => import("./YamlFormatter"), { ssr: false, loading: Loading }),
  "xml-formatter": dynamic(() => import("./XmlFormatter"), { ssr: false, loading: Loading }),
  "csv-viewer": dynamic(() => import("./CsvViewer"), { ssr: false, loading: Loading }),
  "sql-formatter": dynamic(() => import("./SqlFormatter"), { ssr: false, loading: Loading }),
  "regex-tester": dynamic(() => import("./RegexTester"), { ssr: false, loading: Loading }),
  "uuid-generator": dynamic(() => import("./UuidGenerator"), { ssr: false, loading: Loading }),
  "guid-validator": dynamic(() => import("./GuidValidator"), { ssr: false, loading: Loading }),
  "hash-generator": dynamic(() => import("./HashGenerator"), { ssr: false, loading: Loading }),
  "md5-hash-generator": dynamic(() => import("./Md5Hash"), { ssr: false, loading: Loading }),
  "sha256-hash-generator": dynamic(() => import("./Sha256Hash"), { ssr: false, loading: Loading }),
  "sha512-hash-generator": dynamic(() => import("./Sha512Hash"), { ssr: false, loading: Loading }),
  "jwt-decoder": dynamic(() => import("./JwtDecoder"), { ssr: false, loading: Loading }),
  "jwt-generator": dynamic(() => import("./JwtGenerator"), { ssr: false, loading: Loading }),
  "jwt-inspector": dynamic(() => import("./JwtInspector"), { ssr: false, loading: Loading }),
  "jwt-expiry-viewer": dynamic(() => import("./JwtExpiryViewer"), { ssr: false, loading: Loading }),
  "cron-generator": dynamic(() => import("./CronGenerator"), { ssr: false, loading: Loading }),
  "cron-parser": dynamic(() => import("./CronParser"), { ssr: false, loading: Loading }),
  "qr-scanner": dynamic(() => import("./QrScanner"), { ssr: false, loading: Loading }),
  "barcode-generator": dynamic(() => import("./BarcodeGenerator"), { ssr: false, loading: Loading }),
  "url-parser": dynamic(() => import("./UrlParser"), { ssr: false, loading: Loading }),
  "dns-lookup": dynamic(() => import("./DnsLookup"), { ssr: false, loading: Loading }),
  "ip-lookup": dynamic(() => import("./IpLookup"), { ssr: false, loading: Loading }),
  "user-agent-parser": dynamic(() => import("./UserAgentParser"), { ssr: false, loading: Loading }),
  "http-status-codes": dynamic(() => import("./HttpStatusCodes"), { ssr: false, loading: Loading }),
  "mime-types": dynamic(() => import("./MimeTypes"), { ssr: false, loading: Loading }),
  "color-converter": dynamic(() => import("./ColorConverter"), { ssr: false, loading: Loading }),
  "minify-css": dynamic(() => import("./MinifyCss"), { ssr: false, loading: Loading }),
  "minify-js": dynamic(() => import("./MinifyJs"), { ssr: false, loading: Loading }),
  "beautify-html": dynamic(() => import("./BeautifyHtml"), { ssr: false, loading: Loading }),
  "diff-viewer": dynamic(() => import("./DiffViewer"), { ssr: false, loading: Loading }),
  "qr-code-generator": dynamic(() => import("./QrCodeGenerator"), { ssr: false, loading: Loading }),
  "unit-converter": dynamic(() => import("./UnitConverter"), { ssr: false, loading: Loading }),
  "percentage-calculator": dynamic(() => import("./PercentageCalculator"), { ssr: false, loading: Loading }),
  "age-calculator": dynamic(() => import("./AgeCalculator"), { ssr: false, loading: Loading }),
  // Phase 2
  "loan-calculator": dynamic(() => import("./LoanCalculator"), { ssr: false, loading: Loading }),
  "gst-calculator": dynamic(() => import("./GstCalculator"), { ssr: false, loading: Loading }),
  "bmi-calculator": dynamic(() => import("./BmiCalculator"), { ssr: false, loading: Loading }),
  "currency-converter": dynamic(() => import("./CurrencyConverter"), { ssr: false, loading: Loading }),
  "pdf-to-jpg": dynamic(() => import("./PdfToJpg"), { ssr: false, loading: Loading }),
  "pdf-to-word": dynamic(() => import("./PdfToWord"), { ssr: false, loading: Loading }),
  "video-frame-extractor": dynamic(() => import("./VideoFrameExtractor"), { ssr: false, loading: Loading }),
  "video-converter": dynamic(() => import("./VideoConverter"), { ssr: false, loading: Loading }),
  "compress-video": dynamic(() => import("./VideoCompressor"), { ssr: false, loading: Loading }),
  "trim-video": dynamic(() => import("./VideoTrimmer"), { ssr: false, loading: Loading }),
  "extract-audio": dynamic(() => import("./VideoAudioExtractor"), { ssr: false, loading: Loading }),
  "video-to-gif": dynamic(() => import("./VideoToGif"), { ssr: false, loading: Loading }),
  "video-speed-changer": dynamic(() => import("./VideoSpeedChanger"), { ssr: false, loading: Loading }),
  "audio-converter": dynamic(() => import("./AudioConverter"), { ssr: false, loading: Loading }),
  "youtube-downloader": dynamic(() => import("./YoutubeDownloader"), { ssr: false, loading: Loading }),
  // Audio
  "mp3-converter": dynamic(() => import("./Mp3Converter"), { ssr: false, loading: Loading }),
  "trim-audio": dynamic(() => import("./TrimAudio"), { ssr: false, loading: Loading }),
  "volume-booster": dynamic(() => import("./VolumeBooster"), { ssr: false, loading: Loading }),
  "audio-joiner": dynamic(() => import("./AudioJoiner"), { ssr: false, loading: Loading }),
  "voice-recorder": dynamic(() => import("./VoiceRecorder"), { ssr: false, loading: Loading }),
  // Time
  "world-clock": dynamic(() => import("./WorldClock"), { ssr: false, loading: Loading }),
  "stopwatch": dynamic(() => import("./Stopwatch"), { ssr: false, loading: Loading }),
  "timer": dynamic(() => import("./Timer"), { ssr: false, loading: Loading }),
  "alarm": dynamic(() => import("./AlarmClock"), { ssr: false, loading: Loading }),
  "countdown": dynamic(() => import("./Countdown"), { ssr: false, loading: Loading }),
  "date-difference": dynamic(() => import("./DateDifference"), { ssr: false, loading: Loading }),
  "working-days-calculator": dynamic(() => import("./WorkingDays"), { ssr: false, loading: Loading }),
  "time-zone-converter": dynamic(() => import("./TimeZoneConverter"), { ssr: false, loading: Loading }),
  "unix-timestamp-converter": dynamic(() => import("./UnixTimestamp"), { ssr: false, loading: Loading }),
  // Random
  "random-number": dynamic(() => import("./RandomNumber"), { ssr: false, loading: Loading }),
  "random-password": dynamic(() => import("./PasswordGenerator"), { ssr: false, loading: Loading }),
  "random-name": dynamic(() => import("./RandomName"), { ssr: false, loading: Loading }),
  "dice": dynamic(() => import("./Dice"), { ssr: false, loading: Loading }),
  "coin-flip": dynamic(() => import("./CoinFlip"), { ssr: false, loading: Loading }),
  "spin-wheel": dynamic(() => import("./SpinWheel"), { ssr: false, loading: Loading }),
  "team-generator": dynamic(() => import("./TeamGenerator"), { ssr: false, loading: Loading }),
  "decision-maker": dynamic(() => import("./DecisionMaker"), { ssr: false, loading: Loading }),
  "random-color": dynamic(() => import("./RandomColor"), { ssr: false, loading: Loading }),
  "random-country": dynamic(() => import("./RandomCountry"), { ssr: false, loading: Loading }),
  "random-emoji": dynamic(() => import("./RandomEmoji"), { ssr: false, loading: Loading }),
  "random-quote": dynamic(() => import("./RandomQuote"), { ssr: false, loading: Loading }),
  // Investments
  "sip-calculator": dynamic(() => import("./SipCalculator"), { ssr: false, loading: Loading }),
  "step-up-sip-calculator": dynamic(() => import("./StepUpSip"), { ssr: false, loading: Loading }),
  "step-down-sip-calculator": dynamic(() => import("./StepDownSip"), { ssr: false, loading: Loading }),
  "lumpsum-calculator": dynamic(() => import("./LumpsumCalculator"), { ssr: false, loading: Loading }),
  "swp-calculator": dynamic(() => import("./SwpCalculator"), { ssr: false, loading: Loading }),
  "stp-calculator": dynamic(() => import("./StpCalculator"), { ssr: false, loading: Loading }),
  "goal-based-investment-calculator": dynamic(() => import("./GoalCalculator"), { ssr: false, loading: Loading }),
  "inflation-adjusted-sip-calculator": dynamic(() => import("./InflationSip"), { ssr: false, loading: Loading }),
  "mutual-fund-returns-calculator": dynamic(() => import("./MutualFundReturns"), { ssr: false, loading: Loading }),
  "cagr-calculator": dynamic(() => import("./CagrCalculator"), { ssr: false, loading: Loading }),
  "xirr-calculator": dynamic(() => import("./XirrCalculator"), { ssr: false, loading: Loading }),
  "absolute-return-calculator": dynamic(() => import("./AbsoluteReturn"), { ssr: false, loading: Loading }),
  "annualized-return-calculator": dynamic(() => import("./AnnualizedReturn"), { ssr: false, loading: Loading }),
  "investment-growth-calculator": dynamic(() => import("./InvestmentGrowth"), { ssr: false, loading: Loading }),
  "future-value-calculator": dynamic(() => import("./FutureValue"), { ssr: false, loading: Loading }),
  "present-value-calculator": dynamic(() => import("./PresentValue"), { ssr: false, loading: Loading }),
  "rule-of-72-calculator": dynamic(() => import("./RuleOf72"), { ssr: false, loading: Loading }),
  "rule-of-114-calculator": dynamic(() => import("./RuleOf114"), { ssr: false, loading: Loading }),
  "rule-of-144-calculator": dynamic(() => import("./RuleOf144"), { ssr: false, loading: Loading }),
  // Fixed Income
  "fd-calculator": dynamic(() => import("./FdCalculator"), { ssr: false, loading: Loading }),
  "rd-calculator": dynamic(() => import("./RdCalculator"), { ssr: false, loading: Loading }),
  "ppf-calculator": dynamic(() => import("./PpfCalculator"), { ssr: false, loading: Loading }),
  "epf-calculator": dynamic(() => import("./EpfCalculator"), { ssr: false, loading: Loading }),
  "nps-calculator": dynamic(() => import("./NpsCalculator"), { ssr: false, loading: Loading }),
  "sukanya-samriddhi-calculator": dynamic(() => import("./SukanyaCalculator"), { ssr: false, loading: Loading }),
  "senior-citizen-savings-calculator": dynamic(() => import("./ScssCalculator"), { ssr: false, loading: Loading }),
  "nsc-calculator": dynamic(() => import("./NscCalculator"), { ssr: false, loading: Loading }),
  "kisan-vikas-patra-calculator": dynamic(() => import("./KvpCalculator"), { ssr: false, loading: Loading }),
  "post-office-mis-calculator": dynamic(() => import("./PomisCalculator"), { ssr: false, loading: Loading }),
  "treasury-bill-calculator": dynamic(() => import("./TreasuryBillCalculator"), { ssr: false, loading: Loading }),
  "bond-yield-calculator": dynamic(() => import("./BondYieldCalculator"), { ssr: false, loading: Loading }),
  // Loans
  "emi-calculator": dynamic(() => import("./EmiCalculator"), { ssr: false, loading: Loading }),
  "home-loan-calculator": dynamic(() => import("./HomeLoanCalculator"), { ssr: false, loading: Loading }),
  "car-loan-calculator": dynamic(() => import("./CarLoanCalculator"), { ssr: false, loading: Loading }),
  "bike-loan-calculator": dynamic(() => import("./BikeLoanCalculator"), { ssr: false, loading: Loading }),
  "personal-loan-calculator": dynamic(() => import("./PersonalLoanCalculator"), { ssr: false, loading: Loading }),
  "education-loan-calculator": dynamic(() => import("./EducationLoanCalculator"), { ssr: false, loading: Loading }),
  "gold-loan-calculator": dynamic(() => import("./GoldLoanCalculator"), { ssr: false, loading: Loading }),
  "business-loan-calculator": dynamic(() => import("./BusinessLoanCalculator"), { ssr: false, loading: Loading }),
  "loan-eligibility-calculator": dynamic(() => import("./LoanEligibility"), { ssr: false, loading: Loading }),
  "loan-affordability-calculator": dynamic(() => import("./LoanAffordability"), { ssr: false, loading: Loading }),
  "loan-comparison-calculator": dynamic(() => import("./LoanComparison"), { ssr: false, loading: Loading }),
  "loan-prepayment-calculator": dynamic(() => import("./LoanPrepayment"), { ssr: false, loading: Loading }),
  "loan-balance-calculator": dynamic(() => import("./LoanBalance"), { ssr: false, loading: Loading }),
  "loan-amortization-schedule": dynamic(() => import("./LoanAmortization"), { ssr: false, loading: Loading }),
  "interest-only-loan-calculator": dynamic(() => import("./InterestOnlyLoan"), { ssr: false, loading: Loading }),
  "reducing-balance-calculator": dynamic(() => import("./ReducingBalance"), { ssr: false, loading: Loading }),
  // Credit Cards
  "credit-card-emi-calculator": dynamic(() => import("./CreditCardEmi"), { ssr: false, loading: Loading }),
  "credit-card-payoff-calculator": dynamic(() => import("./CreditCardPayoff"), { ssr: false, loading: Loading }),
  "minimum-payment-calculator": dynamic(() => import("./MinimumPayment"), { ssr: false, loading: Loading }),
  "interest-cost-calculator": dynamic(() => import("./InterestCost"), { ssr: false, loading: Loading }),
  "balance-transfer-calculator": dynamic(() => import("./BalanceTransfer"), { ssr: false, loading: Loading }),
  // Savings
  "savings-goal-calculator": dynamic(() => import("./SavingsGoal"), { ssr: false, loading: Loading }),
  "emergency-fund-calculator": dynamic(() => import("./EmergencyFund"), { ssr: false, loading: Loading }),
  "city-emergency-fund-calculator": dynamic(() => import("./CityEmergencyFund"), { ssr: false, loading: Loading }),
  "retirement-corpus-calculator": dynamic(() => import("./RetirementCorpus"), { ssr: false, loading: Loading }),
  "fire-calculator": dynamic(() => import("./FireCalc"), { ssr: false, loading: Loading }),
  "coast-fire-calculator": dynamic(() => import("./CoastFire"), { ssr: false, loading: Loading }),
  "lean-fire-calculator": dynamic(() => import("./LeanFire"), { ssr: false, loading: Loading }),
  "barista-fire-calculator": dynamic(() => import("./BaristaFire"), { ssr: false, loading: Loading }),
  "financial-independence-calculator": dynamic(() => import("./FinancialIndependence"), { ssr: false, loading: Loading }),
  "college-savings-calculator": dynamic(() => import("./CollegeSavings"), { ssr: false, loading: Loading }),
  "vacation-savings-calculator": dynamic(() => import("./VacationSavings"), { ssr: false, loading: Loading }),
  // Study
  "flashcards": dynamic(() => import("./Flashcards"), { ssr: false, loading: Loading }),
  "pomodoro-timer": dynamic(() => import("./PomodoroTimer"), { ssr: false, loading: Loading }),
  "gpa-calculator": dynamic(() => import("./GpaCalculator"), { ssr: false, loading: Loading }),
  "citation-generator": dynamic(() => import("./CitationGenerator"), { ssr: false, loading: Loading }),
  "equation-solver": dynamic(() => import("./EquationSolver"), { ssr: false, loading: Loading }),
  "periodic-table": dynamic(() => import("./PeriodicTable"), { ssr: false, loading: Loading }),
};

export default function ToolRenderer({ slug }: { slug: string }) {
  const Component = COMPONENTS[slug];
  if (!Component) {
    return <p className="text-[var(--muted)]">This tool is coming soon.</p>;
  }
  return <Component />;
}
